version: '3.5'
services:

  # Flask application container configuration
  web:
    build:
      context: ./flask
    ports:
      - "5005:5000"
    depends_on:
      - db

  # Redis database container configuration
  db:
    image: "redis:6.2.6-alpine"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning

    
# Configuration of docker volumes
volumes:
  redis-data:
# A user-defined bridge is created by default




